name: Hello world!
on:
  push:
    branches:
      - master

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/cowsay-action@v1.x
        with:
          text: "I am not a developer!"
