- name: Cowsays
  uses: mscoutermarsh/cowsays-action@v1
  with:
    # What does the cow say?
    text: # optional, default is Ship it!!!!!
    # Color of your cow
    color: # optional, default is white
